### ISSUE TITLE
Feature request: disable whitespace skipping between > and node content

### ISSUE THREAD

**Issue by tombenes** [Fe-Bell/RapidXML#11]
While parsing some opendocument files I've encountered problem with nodes containing single space character.
I've narrowed it down to `skip<whitespace_pred, Flags>(text);` in `rapidxml/rapidxml.hpp:2174`.
As for now, I see no option to disable it, although there is `parse_trim_whitespace` flag, that should enable skipping, but it occurs without one, so it might be a bug.

**Comment by Fe-Bell** [comment]
Thanks for reporting. I haven't had much time to look into this, but will check the code when I'm able to. Please let me know if you have any suggestions.

**Comment by Fe-Bell** [comment]
I believe this was fixed with PR #12. Available with RapidXML v1.17.

We can open this again if you find any issues.
